#!/usr/bin/env bash

cd /usr/lib/catbot

case $1 in
  start|stop|update)
    exec "./${1}"
    ;;
  accounts)
    xdg-open accounts.txt &
    ;;
  ipc-password)
    cat /tmp/cat-webpanel-password
    ;;
  cathook)
    cd cathook
    exec ./attach
    ;;
  *)
    echo Usage: catbot [OPTIONS]
    echo options: start stop update accounts ipc-password cathook
    ;;
esac
