#!/usr/bin/env bash

cd $CATS_HOME

CATDIR="$(find -name catbot)"

if [ ! -d $CATDIR ]; then
  echo "Error: Installation Path (CATS_HOME) is BROKEN, Fix IT!"
  exit
fi

cd $CATDIR

case $1 in
  start|stop|update|uninstall)
    exec "./${1}"
    ;;
  accounts)
    xdg-open accounts.txt &
    ;;
  ipc-password)
    cat /tmp/cat-webpanel-password
    ;;
  *)
    echo "  usage: catbot <operation>"
    echo "  operations:"
    echo "      start               start the bots"
    echo "      stop                stop them"
    echo "      update              update catbots"
    echo "      uninstall           uninstall catbots"
    echo "      accounts            edit the accounts list (should follow the username:password format)"
    echo "      ipc-password        prints your IPC webpanel password to the terminal"
    ;;
esac
