#!/usr/bin/env bash

if [ "$CATHOOK_HOME" = "" ]; then
  source /etc/profile
fi

cd $CATHOOK_HOME

if [ ! -d cathook ]; then
  echo "Error: Installation Path (CATHOOK_HOME) is BROKEN, Fix IT!"
  exit
fi

cd cathook

case $1 in
  attach)
    sudo "./${1}"
    ;;
  preload|update|config)
    exec "./${1}"
    ;;
  uninstall)
    sudo rm -rf ../cathook
    sudo rm -rf /usr/bin/cathook
    ;;
  *)
    echo "  usage: cathook <operation>"
    echo "  operations:"
    echo "      attach              Attach (inject) Cat Hax"
    echo "      preload             Preload cathook or something"
    echo "      update              Update cathook"
    echo "      config              Open config dialog"
    echo "      uninstall           Uninstall cathook"
    ;;
esac
