#!/usr/bin/env bash

cd $CATS_HOME

CATDIR="$(find -maxdepth 2 -type d -name cathook)"

if [ ! -d $CATDIR ]; then
  echo "Error: Installation Path (CATS_HOME) is BROKEN, Fix IT!"
  exit
fi

cd $CATDIR

case $1 in
  attach|preload|update)
    sudo "./${1}"
    ;;
  uninstall)
    sudo rm -rf ../cathook
    sudo rm -rf /usr/bin/cathook
    ;;
  *)
    echo "  usage: cathook <operation>"
    echo "  operations:"
    echo "      attach              Attach (inject) Cat Hax"
    echo "      preload             Preload cathook or something"
    echo "      update              Update cathook"
    echo "      uninstall           Uninstall cathook"
    ;;
esac
